# Generated by Django 5.1 on 2025-03-08 08:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('est_terminee', models.BooleanField(default=False)),
                ('user_admin', models.CharField(max_length=200)),
                ('collaborateurs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TacheRegroupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('est_terminee', models.BooleanField(default=False)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regroupements', to='taches.projet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_username', models.CharField(blank=True, max_length=150, null=True)),
                ('last_login', models.DateField(default=datetime.datetime.today)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('coins', models.IntegerField(default=0)),
                ('pp', models.ImageField(default='images/pp/steve_default.jpg', upload_to='images/pp/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('est_terminee', models.IntegerField(default=0)),
                ('duree', models.IntegerField(default=2)),
                ('dependantes', models.ManyToManyField(blank=True, to='taches.tache')),
                ('regroupement', models.ManyToManyField(related_name='taches', to='taches.tacheregroupement')),
                ('assignee_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taches.userprofile')),
            ],
        ),
    ]
