# Generated by Django 5.1 on 2025-03-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='assignee_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taches.userprofile'),
        ),
    ]
