# Generated by Django 5.1 on 2025-03-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0004_chatprojet_chatregroupement_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='taches.chatprojet'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat_regroupement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='taches.chatregroupement'),
        ),
    ]
