# Generated by Django 5.1.7 on 2025-03-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taches", "0005_alter_messages_chat_projet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="date_fini",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
